### ISSUE TITLE
Every time I do everything there are errors

### ISSUE THREAD

**Issue by svencode06** [FinlayCameroon/Assistant#1]
![Schermopname (1)](https://user-images.githubusercontent.com/126981268/222923392-ef081ca8-57a7-4e09-bde3-cb262f790a22.png)

does anyone know how i can solve this?

**Comment by FinlayCameroon** [comment]
You need to pip install all the packages and then make sure that python 3.8 is your selected interpreter

**Comment by svencode06** [comment]
aah thanks man this helps me a lot i have to install this via command prompt and run it in studio code?

**Comment by FinlayCameroon** [comment]
Yes but you can run it through other environments which support python

**Comment by svencode06** [comment]
ah okay like which one

**Comment by FinlayCameroon** [comment]
I personally run most my code through the terminal but vscode's integrated terminal will do exact same thing as opening a separate terminal window

**Comment by svencode06** [comment]
you mean the terminal of your laptop or a terminal of another app

**Comment by FinlayCameroon** [comment]
What do you mean by "another app" guessing an environment like anaconda

**Comment by svencode06** [comment]
yeah thats what i mean

**Comment by svencode06** [comment]
so i want an assistant that i can run my phone on

**Comment by FinlayCameroon** [comment]
Yes it will run fine on anaconda

**Comment by FinlayCameroon** [comment]
I would recommend learning how to code more in depth before trying to use other peoples code as you will be able to edit it for your own uses

**Comment by svencode06** [comment]
yes that might be useful I've been doing this for 2 months now and I now know a bit so then it will be a bit of learning
